### ISSUE TITLE
FASA seems to need RealChutes

### ISSUE THREAD

**Issue by bthylafh** [KSP-RO/FASA-RO#18]
I'm using KSP 1.2.2 with a relatively clean install: MechJeb, Kerbal Engineer, FASA 7.1.  It appears that FASA's parachutes don't provide enough drag to safely land unless I also install RealChutes.

For example: I made a bare Mercury capsule with the large Mercury parachute, the nose cone, and escape tower, then put it on the launch pad and hit abort to fire the LES.  Once it was done firing, I staged until the parachute deployed.  Without RC the capsule hit the ground at ~70 m/s, chute fully deployed.  With RC the same craft made a safe landing at ~3 m/s.  Same thing happens with a proper Mercury launch, or Gemini, or Apollo.

I checked the KSP forum thread and didn't see any mention of RealChute in the original post besides the patch to fix an issue with the Apollo parachutes.

**Comment by stratochief66** [comment]
With stock, or in RSS/RO? With or without FAR?

If you want to come up with configs for the chutes that work with stock chutes, feel free and PR them. We'll test them and accept them if they work. I just focus on how things work in RSS/RO/BBQ/WTF (with all the fixings), but we're more than interested to include fixes that make things work that are broken in stock.

**Comment by bthylafh** [comment]
Just plain stock; RO isn't my thing, nor is FAR, and I'm lazy enough that I'd rather let CKAN manage my packages.

I'm a total newbie to modding KSP.  I assume that (were I to submit fixes) that I'd need to edit e.g. Merc_Parachute.cfg; I see a lines in there called semiDeployedDrag and fullyDeployed Drag.  Are those what I'd need to edit and test?  Or should I look elsewhere?

Unrelated: I imported assembled vehicles from FASA 5.44 and (so far) all of them seem to work more-or-less correctly with 7.1/stock, with the notable exception of the LEM's door being obstructed, so EVA's impossible.

**Comment by stratochief66** [comment]
IIRC, the model for the LEM requires RPM to not have the obstruction problem?

https://github.com/KSP-RO/FASA-RO/blob/master/GameData/FASA/Mercury/FASA_Mercury_Parachute_Box/Merc_Parachute.cfg

Yep, that is where you would modify the part. Normally, in a mod like RO we make changes through a 'patch' rather than directly to the part file, but since you want to change how the part behaves in a fully stock environment, what you've said is the right way to do it.

There appear to be some bits of code commented out there. The bits with // before them won't be active. You could also try removing all of the //, and see if that is enough to solve the problem?

**Comment by raidernick** [comment]
fixed https://github.com/KSP-RO/FASA-RO/pull/31
