### ISSUE TITLE
No Ship craft save files

### ISSUE THREAD

**Issue by kgb61393** [KSP-RO/FASA-RO#20]
Hello, there is no folder with craft files for non RO use. Can you please put in the mod a ship folder with non RO FASA craft ? thank's :)

**Comment by stratochief66** [comment]
I don't play stock, so I wouldn't ever be making stock craft files myself. The reason that RO has FASA craft files is because I play RO with FASA, so I make those craft anyway. I figured since I'm already doing the work for myself, I may as well put them where other people can get them as well.

If someone is nice enough to build craft files for stock FASA and make a Pull Request to send them to us, I would definitely be interested enough to test them and make them shareable.

**Comment by raidernick** [comment]
craft files will likely not be added again because they need to be remade on game updates or minor changes to parts
