### ISSUE TITLE
RCS Thruster in 1.4.2

### ISSUE THREAD

**Issue by MikeLyno** [KSP-RO/FASA-RO#33]
Can't do with this mod. I recently reluctantly (cause I was worried the FASA mod might not work right) upgraded from 1.3.1 to 1.4.2. Now when trying to play an Apollo save game, the FASA RCS thrusters (including Apollo APS flight pack when used as thrusters) are going wild shooting while plume out further than the ship and whiting out everything. Is there a way for me to fix this? This is a game buster for me as I can't playing without the FASA parts as yours is far and away the best by a long shot. Please help. Thanks

**Comment by raidernick** [comment]
The mod clearly says it doesn't support 1.4.2, I clearly said it doesn't support 1.4.2 and this is an invalid issue as you are clearly using 1.4.2 and not the version of the game it was released for. Either use the correct version of KSP for the mod or don't use the mod until it's updated for that version of KSP.

**Comment by MikeLyno** [comment]
Ok. I thought there might have been a workaround, it's why I asked. Sorry

**Comment by ghost** [comment]
So, it's been almost two years, but since FASA hasn't been updated, I thought I'd just leave this here:
I have just created a module manager patch that fixes this issue for all older mods, you can download 

*removed link*

As far as I can tell, nobody else has done something like this yet(**EDIT: Except I have and this issue has been fixed a long time ago had you bothered to check**), even though it was actually rather simple, and I'm now going around trying to find people who may need it. Feel free to share the link, but it would be appreciated if you could credit me when you do.

**Comment by raidernick** [comment]
The mod was updated last 24 days ago(so don't act like it's not being maintained) and this issue, which was posted 2 years ago, was fixed in march of last year here: https://github.com/KSP-RO/FASA-RO/commit/ddd32fd0bbe7b26a38708215781038245bc582f2

Don't spread misinformation on old issues that have long been resolved.

**Comment by ghost** [comment]
So, I made a huge mistake, but it's not the mistake that you think I made. In any case, you are absolutely right to be furious at me.

So, the mistake I made was that I entirely forgot to regard the fact that I am running KSP 1.4.
This means that, for me, updated versions of FASA/FASA light aren't compatible, because they were released after v1.8.1 of KSP as far as I can tell right now (I researched this in depth when I tried to find a version of FASA that would work properly for 1.4), which is why I wanted to get an older one working.
This incredibly important fact completely slipped my mind at the time of posting, so I am a blistering idiot who should really not be commenting on github.
And I will admit that I hadn't found your fix, which would have made it easier to write the MM patch.
Nonetheless, from what I can tell, and I did research this, also checking just now if such a patch is included in FASA light, there hasn't been a MM patch that fixes the RCS issue in general for everything (even though it is admittedly rather obvious and easy to write, so most people who need it can write it themselves). This is what I was referring to when saying that, as far as I can tell, nobody else has done something like this yet. The phrasing here was terrible, this isn't the right thread for this because the specific issues for this mod have been fixed previously, and I completely fucked up my first and last contribution to github.

I'm not a programmer, just an idiot, and it shows.
